name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      placeholder: "8.2"
    validations:
      required: true

  - type: input
    id: laravel-version
    attributes:
      label: Laravel Version
      placeholder: "11.0"
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Query Doctor Version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database Driver
      placeholder: "MySQL 8.0 / PostgreSQL 16 / SQLite"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: Steps, code, or a minimal reproduction repository.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste any relevant logs here.
      render: shell
